services:
  pve:
    image: makedie/proxmox_ve:8.3.1
    container_name: pve-8.3.1
    tty: true
    environment:
      root_password: "root"
      #port: 9527
    devices:
      - /dev/dri
      - /dev/fuse
      - /dev/kvm
      - /dev/vfio
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-vgpu1
    cap_add:
      #- SYS_ADMIN
      - NET_ADMIN
    ports:
      - 8006:8006
    #network_mode: host
    volumes:
      #- /sys/fs/cgroup:/sys/fs/cgroup:ro
      #- /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd
      - /sys/fs/fuse:/sys/fs/fuse
      - /var/run/openvswitch:/host/var/run/openvswitch
      # - /usr/dockerFile/pve/pve-cluster:/var/lib/pve-cluster
      # - /usr/dockerFile/pve/vz:/var/lib/vz
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache
      - /run/lock
    extra_hosts:
      - "shop.maurer-it.com:127.0.0.1"
      #- "pve:192.168.6.66"
    hostname: pve
    stop_grace_period: 2m
    privileged: true