#!/bin/bash
case $1 in
-r)
        echo "$(echo "$fake_uname_a" | sed -E 's/^[^ ]+ [^ ]+ ([^ ]+) .*/\1/')"
;;
-a)
        echo "$fake_uname_a"
;;
-v)
        echo "$(echo "$fake_uname_a" | sed -E 's/^[^ ]+ [^ ]+ [^ ]+ (.*)/\1/')"
;;
-m)
        echo "$fake_uname_a" | awk '{print $(NF-1)}'
;;
-p)
	echo unknown
;;
-i)
	echo unknown
;;
-s)
	echo Linux
;;
-o)
	echo "GNU/Linux"
;;
-n)
	hostname
;;
esac

if [ -z $1 ]; then
	echo Linux
fi