FROM debian:bookworm-20240812 as builder1
#base mirrow
ARG DEBIAN_FRONTEND=noninteractive
RUN echo "root:root"|chpasswd && \
    apt update &&\
    apt install -y --no-install-recommends ca-certificates && \
    sed -i 's/http:/https:/g' /etc/apt/sources.list.d/debian.sources && \
    apt update
RUN apt install -y systemd && \
    apt install -y --no-install-recommends wget curl screen vim busybox &&\
    busybox --install
RUN wget http://download.liveupdate.fnnas.com/x86_64/trim/TRIM-0.8.13-300.deb &&\
    dpkg -i TRIM-0.8.13-300.deb &&\
    rm -f TRIM-0.8.13-300.deb
RUN apt install -y --no-install-recommends postgresql-15 libpci-dev \
    libsqlite3-0 libbluray2 libsmbclient libturbojpeg0 \
    libtcmalloc-minimal4 libopenmpt0 libyuv0 libnl-3-200 libzmq5 libglib2.0-0 \
    libvpx7 libnm0 libexiv2-27 libaio1 libmagick++-6.q16-8 libwebpmux3 \
    libnl-route-3-200 libupnp13 dmidecode libraw20 libzvbi0
COPY etc.tar /usr/trim
RUN ls -l /usr/trim && tar -xf /usr/trim/etc.tar -C /usr/trim

RUN ln -s /usr/trim/lib/libndev.so /usr/lib/x86_64-linux-gnu/libndev.so && \
    ln -s /usr/trim/lib/libtrimrpc.so.0.1.0 /usr/lib/x86_64-linux-gnu/libtrimrpc.so.0.1.0 && \
    ln -s /usr/trim/lib/libtrim_channel.so.0 /usr/lib/x86_64-linux-gnu/libtrim_channel.so.0 && \
    ln -s /usr/trim/lib/libnperm.so /usr/lib/x86_64-linux-gnu/libnperm.so && \
    ln -s /usr/trim/lib/libppjson.so /usr/lib/x86_64-linux-gnu/libppjson.so && \
    ln -s /usr/trim/lib/libnebula.so /usr/lib/x86_64-linux-gnu/libnebula.so && \
    ln -s /usr/trim/lib/libntoken.so /usr/lib/x86_64-linux-gnu/libntoken.so
RUN rm -rf /usr/sbin/useradd && \
    ln -s /usr/trim/bin/useradd /usr/sbin/useradd
RUN sed -e 's/peer/trust/' -e 's/scram-sha-256/trust/' -i /etc/postgresql/15/main/pg_hba.conf && \
    echo "host trim_connect tc 127.0.0.1/32 trust" >> /etc/postgresql/15/main/pg_hba.conf
RUN echo "Users:x:1001:" >> /etc/group && \
    echo "Administrators:x:1000:" >> /etc/group
RUN rm -rf /etc/systemd/system/multi-user.target.wants/docker.service
STOPSIGNAL SIGINT
CMD [ "/lib/systemd/systemd", "log-level=info", "unit=sysinit.target"]