services:
  fnos:
    image: makedie/fnos:0.8.29-568_test
    container_name: fnOS
    tty: true
    devices:
      - /dev/dri
      - /dev/fuse
      - /dev/kvm
      - /dev/vfio
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-vgpu1
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    ports:
      - 5666:5666
      - 5432:5432
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      #- /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd
      - /sys/fs/fuse:/sys/fs/fuse
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache
      - /run/lock
    extra_hosts:
      - "fnOS:127.0.0.1"
    hostname: fnOS
    privileged: true